# Generated by Django 3.2 on 2021-06-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20210620_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cate',
            new_name='cat',
        ),
    ]
