# Generated by Django 3.2 on 2021-06-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_auto_20210625_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birthday',
            new_name='date_birthday',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='sexo',
            new_name='gender',
        ),
    ]
